const patches = [
	{ name: "cactus", aliases: ["potato cactus", "cactus"] },
	{
		name: "allotment",
		aliases: [
			"potato",
			"onion",
			"cabbage",
			"tomato",
			"sweetcorn",
			"strawberry",
			"watermelon",
			"snape grass",
		],
	},
	{ name: "flower", aliases: ["limpwurt"] },
	{
		name: "hops",
		aliases: [
			"wildblood",
			"krandorian",
			"yanillian",
			"jute",
			"asgarnian",
			"hammerstone",
			"barley",
		],
	},
	{ name: "crystal", aliases: ["crystal tree"] },
	{ name: "belladonna", aliases: ["belladonna"] },
	{
		name: "bush",
		aliases: [
			"redberry",
			"dwellberry",
			"cadavaberry",
			"jangerberry",
			"whiteberry",
			"poison ivy",
		],
	},
	{
		name: "fruit",
		aliases: [
			"apple",
			"banana",
			"orange",
			"curry",
			"pineapple",
			"papaya",
			"palm",
			"coconut",
			"dragonfruit",
		],
	},
	{ name: "hespori", aliases: ["hespori"] },
	{ name: "vine", aliases: ["grape"] },
	{ name: "calquat", aliases: ["calquat"] },
	{ name: "celastrus", aliases: ["celastrus"] },
	{ name: "redwood", aliases: ["red", "redwood"] },
	{ name: "hardwood", aliases: ["teak", "mahogany"] },
	{ name: "seaweed", aliases: ["seaweed"] },
	{
		name: "herb",
		aliases: [
			"guam",
			"marrentill",
			"tarromin",
			"harralander",
			"toadflax",
			"avantoe",
			"irit",
			"ranarr",
			"snapdragon",
			"kwuarm",
			"cadantine",
			"dwarf",
			"dwarf weed",
			"torstol",
			"lantadyme",
		],
	},
	{ name: "tree", aliases: ["oak", "willow", "maple", "yew", "magic"] },
	{ name: "spirit", aliases: ["spirit tree"] },
];

export default patches;
